### ISSUE TITLE
InMobi adapters package v1.0.2 upload appstore exist "UIWebView"

### ISSUE THREAD

**Issue by LongLostPenPal** [mopub/mopub-unity-mediation#126]
1. **What is the issue?**
    > InMobi adapters package v1.0.2 upload appstore exist "UIWebView"

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > Provide the data here
    * **Platform** (*Android, iOS, Unity*)
        > Unity
    * **MoPub SDK Version**
        > 5.16.2
    * **Mediation SDK Name & Version**
        > InMobi (1.0.2-Android.9.1.9.0-iOS.9.1.7.0)
    * **Mediation Adapter Version**
        > Provide the data here
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > Provide the data here
    * **Device model and OS Version**
        > Provide the data here
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. Do this.
        > 2. Do that.
    * **Observed behavior**
        > Provide the data here
    * **Expected behavior** (if known)
        > Provide the data here
    * **Evidence** (if available)
        > [Attach logs (device/network), mini debug builds (source code preferably), stack traces, screenshots / screen recordings, etc.
](url)

**Comment by LongLostPenPal** [comment]
![image](https://github.com/LongLostPenPal/MyPackage/blob/master/%E4%B8%8B%E8%BD%BD.png?raw=true)

**Comment by p158276** [comment]
Hi @LongLostPenPal ,
Thanks for reaching out. Please use the new iOS adapters v9.1.7.2+ or Unity adapters v1.0.5+ so that the Moat module will not be included in the InMobi adapter dependencies.

Yoyo Lin
MoPub Team

**Comment by LongLostPenPal** [comment]
Thanks for the reply !  this problem is fixed after changing the version
