### ISSUE TITLE
UnityAds mediation+Unity 2018+Android=FATAL EXCEPTION: main

### ISSUE THREAD

**Issue by boris-741** [mopub/mopub-unity-mediation#18]
Unity: 2018.1.9
MoPub plugin: 5.2 (5.3 same error)
device: Sumsung Galaxy j2 (Android 6)
UnityAds: mopub-unityads-adapters-2.3.0.0

Raises an error at the start of the rewarded video with unity ads mediation
`MoPub.RequestRewardedVideo(adUnitId: rewardedVideoAdUnits[0], keywords: "rewarded, video");`
Other mediation's work without errors.

error:
08-17 07:38:39.893 13756 13756 E AndroidRuntime: FATAL EXCEPTION: main
08-17 07:38:39.893 13756 13756 E AndroidRuntime: Process: com.urse.seasonmatch, PID: 13756
08-17 07:38:39.893 13756 13756 E AndroidRuntime: java.lang.Error: FATAL EXCEPTION [main]
08-17 07:38:39.893 13756 13756 E AndroidRuntime: Unity version     : 2018.1.9f1
08-17 07:38:39.893 13756 13756 E AndroidRuntime: Device model      : samsung SM-G532F
08-17 07:38:39.893 13756 13756 E AndroidRuntime: Device fingerprint: samsung/grandpplteser/grandpplte:6.0.1/MMB29T/G532FXXU1AQG2:user/release-keys
08-17 07:38:39.893 13756 13756 E AndroidRuntime: 
08-17 07:38:39.893 13756 13756 E AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: com.mopub.mobileads.UnityRewardedVideo$UnityAdsListener
08-17 07:38:39.893 13756 13756 E AndroidRuntime: 	at com.mopub.mobileads.UnityRewardedVideo.<clinit>(UnityRewardedVideo.java:20)
08-17 07:38:39.893 13756 13756 E AndroidRuntime: 	at java.lang.Class.classForName(Native Method)
08-17 07:38:39.893 13756 13756 E AndroidRuntime: 	at java.lang.Class.forName(Class.java:324)
08-17 07:38:39.893 13756 13756 E AndroidRuntime: 	at java.lang.Class.forName(Class.java:285)
08-17 07:38:39.893 13756 13756 E AndroidRuntime: 	at com.mopub.common.util.Reflection.instantiateClassWithEmptyConstructor(Reflection.java:154)
08-17 07:38:39.893 13756 13756 E AndroidRuntime: 	at com.mopub.mobileads.MoPubRewardedVideoManager.onAdSuccess(MoPubRewardedVideoManager.java:527)
08-17 07:38:39.893 13756 13756 E AndroidRuntime: 	at com.mopub.mobileads.MoPubRewardedVideoManager.access$000(MoPubRewardedVideoManager.java:60)
08-17 07:38:39.893 13756 13756 E AndroidRuntime: 	at com.mopub.mobileads.MoPubRewardedVideoManager$RewardedVideoRequestListener.onSuccess(MoPubRewardedVideoManager.java:100)
08-17 07:38:39.893 13756 13756 E AndroidRuntime: 	at com.mopub.network.AdRequest.deliverResponse(AdRequest.java:428)
08-17 07:38:39.893 13756 13756 E AndroidRuntime: 	at com.mopub.network.AdRequest.deliverResponse(AdRequest.java:42)
08-17 07:38:39.893 13756 13756 E AndroidRuntime: 	at com.mopub.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:106)
08-17 07:38:39.893 13756 13756 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
08-17 07:38:39.893 13756 13756 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-17 07:38:39.893 13756 13756 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
08-17 07:38:39.893 13756 13756 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7406)
08-17 07:38:39.893 13756 13756 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-17 07:38:39.893 13756 13756 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
08-17 07:38:39.893 13756 13756 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
[log_mopub_err.txt](https://github.com/mopub/mopub-unity-mediation/files/2306441/log_mopub_err.txt)

**Comment by chauduyphanvu1** [comment]
It looks like the inner class `com.mopub.mobileads.UnityRewardedVideo$UnityAdsListener` (https://github.com/mopub/mopub-android-mediation/blob/75417d4a233a54d3b433bfc409deb39606b3bc07/UnityAds/com/mopub/mobileads/UnityRewardedVideo.java#L110) goes missing in the APK. 

Did you reproduce this crash in our Unity sample app on this repo? Could you reverse-engineer the APK to see if the class is present? If not, feel free to send over your Unity/Android project and we'll be happy to take a look. Thanks!

**Comment by boris-741** [comment]
on your example, the error is repeated. I have to add the UnityRewardedVideo.java class myself to my project?

**Comment by boris-741** [comment]
in apk there are classes
smali\com\mopub\mobileads\UnityRewardedVideo.smali
smali\com\mopub\mobileads\UnityRewardedVideo$1.smali
smali\com\mopub\mobileads\UnityRewardedVideo$UnityAdsListener.smali
smali\com\mopub\mobileads\UnityRewardedVideo$UnityLifecycleListener.smali

**Comment by chauduyphanvu1** [comment]
You don't have to - importing the `mopub-unityads-adapters-2.3.0.0` Unity package automatically imports all the adapter (java) classes. I'm trying to reproduce this in our sample project but currently am not seeing it happening. 

Here's a few other things I'd check:
- See if this crash occurs on another device (running on a different Android version). Are you using multidexing? This could be related to the class loader not being able to locate the necessary class at runtime.
- Check Unity Ads integration steps to see if there are other requirements that might have been missed. Make sure you import the Unity Ads SDK to your Unity project.
- If this problem persists, email us at <support@mopub.com>.

**Comment by boris-741** [comment]
> Check Unity Ads integration steps to see if there are other requirements that might have been missed. Make sure you import the Unity Ads SDK to your Unity project.

Is it enough to add mopub-unityads-adapters-2.3.0.0 to the project?
I have a file in the directory in the project.
\Assets\Plugins\Android\mopub-support\libs\mopub-unityads-adapters-2.3.0.0.jar

http://prntscr.com/kla36j

**Comment by chauduyphanvu1** [comment]
You need to also add the Unity Ads aar to `Assets/Plugins/Android`.

<img width="570" alt="screen shot 2018-08-21 at 11 41 27 am" src="https://user-images.githubusercontent.com/25616035/44412564-3e314200-a537-11e8-9d3b-2241a83b0acf.png">

**Comment by boris-741** [comment]
Thanks to this solved my problem.
