### ISSUE TITLE
Tapjoy Help Wanted

### ISSUE THREAD

**Issue by boris-741** [mopub/mopub-unity-mediation#19]
> Setting Up Tapjoy on MoPub UI
> Requires network SDK greater than version 10.x and adapter
> SDK Key and Placement Name are required

Where do I specify SDK Key and Placement Name in the code?
Is it enough to put a file /Assets/Plugins/Android/mopub-support/libs/tapjoyconnectlibrary.jar in the project?
When I start the tapjoy video, I get an answer: error=No ads found.

**Comment by chauduyphanvu1** [comment]
Hello,

You do not specify those attributes in code. Mediation IDs (placement, keys, etc.) from third-party networks should be obtained from the network dashboards/UI when you sign up for an account, and inputted on the MoPub dashboard/UI at https://app.mopub.com/networks under the corresponding instance for that network (Tapjoy in this case). More detailed instructions are available on https://developers.mopub.com/docs/mediation/networks/tapjoy/. 

Once you've done that, add the Tapjoy adapter Unity package from (https://github.com/mopub/mopub-unity-mediation/tree/master/unity-packages) and the Tapjoy SDK  (tapjoyconnectlibrary.jar) to your Unity project. 

Getting a "no ads found" error usually means it's a "no fill" from that mediation network (check this tutorial for how to interpret device logs: https://developers.mopub.com/docs/android/testing/#i-am-seeing-no-ads-for-ad-unit-or-no-ads-found-in-my-device-logs-what-does-this-mean). It doesn't sound like an adapter issue in this case, so I'd email <support@mopub.com> for additional assistance.

**Comment by boris-741** [comment]
Thank you very much you solved my problem.
