### ISSUE TITLE
Mediation Issue in Unity

### ISSUE THREAD

**Issue by Kingkong302** [mopub/mopub-unity-mediation#20]
i am trying to use ads mediation with others ad networks ,firstly i imported mopub ads plugin and than  imported all adapters and than added this script in test scene,its sending requests(can see in dashboard) but ad is not showing on device,kindly mention where i need to pass rewarded ad id and sdk init_id and other networks ad ids,Please help :(

using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class AdMaster : MonoBehaviour
{
	public string[] _rewardedVideoAdUnits = {
		"Ad_colonyRewarded_Ad_ID",
		"ChartBoost_REwarded_Ad_ID",
		"UNity_REwarded_Ad_ID",
		"VungleRewardedAd_ID",
		"Admob_Rewarded_AD_ID"
	};

// Use this for initialization
	void Start ()
	{			
		var sdkConfig = new MoPub.SdkConfiguration {
			AdUnitId = "Mopub_RewardedAd_ID", // Any ad unit ID your app uses

			// (Optional) A list of rewarded video adapters to initialize
			NetworksToInit = new MoPubBase.RewardedNetwork[] {				
				MoPub.RewardedNetwork.AdColony,
				MoPub.RewardedNetwork.Chartboost,
				MoPub.RewardedNetwork.Unity,
				MoPub.RewardedNetwork.Vungle,
				MoPub.RewardedNetwork.AdMob
			}
		};
		MoPub.InitializeSdk (sdkConfig);

		// Publishers can override MoPubEventListener.OnSdkInitializedEvent() to get a callback.
		// Alternatively, publishers can call "yield return WaitUntil(() => MoPub.IsSdkInitialized)" to suspend the coroutine execution until the SDK has initialized.

		MoPub.LoadRewardedVideoPluginsForAdUnits (_rewardedVideoAdUnits);

	}
	
	// Update is called once per frame
	void Update ()
	{
		
	}
     public void requestAd ()
	{
		MoPub.RequestRewardedVideo ("Mopub_RewardedAd_ID");
	}
	public void showAd ()
	{
              if (MoPub.HasRewardedVideo ("Mopub_RewardedAd_ID")) {
			MoPub.ShowRewardedVideo ("Mopub_RewardedAd_ID");
		} 
	}
}

**Comment by chauduyphanvu1** [comment]
What are some of the ad unit IDs you are using but are not seeing ads? It appears you are using literal strings like `Mopub_RewardedAd_ID` and `Ad_colonyRewarded_Ad_ID`. If that's so, they are not actual MoPub ad unit IDs. Check out this list of sample ad unit IDs we use in our test scene and let us know if they work for you: https://github.com/mopub/mopub-unity-sdk/blob/master/unity-sample-app/Assets/Scripts/MoPubDemoGUI.cs#L24-L40. You can also run the test scene as-is to get an understanding of the ad lifecycle and workflow.

If you still don't see ads, attach your device logs for the OS you are building for, and we'll be happy to assist you further.

**Comment by Kingkong302** [comment]
Thanks for your response.
As you mentioned in your response, I am already using actual IDs for respected networks in script. It is just a template which I posted you.
I have also used sample you mentioned above with my own mopub id, but it is crashed when i send request for rewarded video.
So 
1. I am not clear about my script i.e. is it OK or NOT (Admaster.cs)
2. Why sample app crashed when I replaced my mopub rewarded video ID with given demo ID.
3. Can you help me to integrate multiple networks in given sample script such as admob, vungle and chartboost, because given sample script only help to integrate only mopub network.

**Comment by chauduyphanvu1** [comment]
Do you have the stack trace for that crash? Which platform (Android or iOS) are you building for? It'll be easier to debug the issue with a stack trace and/or device logs, so feel free to post them here.

Your script seems OK, but there might be issues with integrating the actual mediation network SDKs in your project. Check this tutorial to make sure you have followed the right steps: https://developers.mopub.com/docs/unity/getting-started/. You won't need to modify your script for mediation - the MoPub SDK will handle it on your behalf. [The sample script](https://github.com/mopub/mopub-unity-sdk/blob/master/unity-sample-app/Assets/Scripts/MoPubDemoGUI.cs) can be used - just populate it with your mediation ad unit IDs.

**Comment by Kingkong302** [comment]
@chauduyphanvu1 thankx for your response,i have added sdk of each ad network with adopters and now its was working with unity mediation,But when i added sdk of admob or vungle or adcolony,it gives the error when i try to build.
![error](https://user-images.githubusercontent.com/39819701/46013312-5885af00-c0e5-11e8-9dfb-48bccbaef2c4.PNG)

-----------------Error Log------------------
UnityEditor.BuildPlayerWindow+BuildMethodException: 3 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (BuildPlayerOptions options) [0x0020e] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:181 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (Boolean askForBuildLocation, BuildOptions defaultBuildOptions) [0x00065] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:88 
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

------------------------------------------------
Please guide me how can i remove this error.
Thankyou.

**Comment by chauduyphanvu1** [comment]
Follow up with a more granular fix: This issue originates from the AdColony Unity plugin including an additional v4 support lib jar ("support-v4-24.0.0" in /libs). We already include it in [our Unity plugin](https://github.com/mopub/mopub-unity-sdk/blob/1f96e3603f3b9c56d1e327013e85e50b5be0a2aa/scripts/mopub-android-sdk-unity-build.sh#L61-L62). Remove one of them (preferably the AdColony copy), and export the Unity project. That should resolve this duplicate resources error.

**Comment by Kingkong302** [comment]
@chauduyphanvu1  i have tried it with chartboost, admob and vungle as well one by one,its giving the same error :(

**Comment by Kingkong302** [comment]
Should i remove support-v4.jar files only?

**Comment by aornelas** [comment]
yes, start with that 😉

**Comment by aornelas** [comment]
please post any logs/errors that you are seeing, and we'll look into it.

thanks!

**Comment by Kingkong302** [comment]
![error](https://user-images.githubusercontent.com/39819701/46057362-c1653980-c16e-11e8-8cb2-dc9a28027813.PNG)
-----------------------Error Log-------------------------

CommandInvokationFailure: Gradle build failed. 
C:/Program Files/Java/jdk1.8.0_181\bin\java.exe -classpath "C:\Program Files\Unity 2017.4.1f1\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-4.0.1.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx2048m" "assembleRelease"

stderr[

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForRelease'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 19s
]
stdout[
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to G:\android-sdks\ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to G:\android-sdks\ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

The setTestClassesDir(File) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the setTestClassesDirs(FileCollection) method instead.
The getTestClassesDir() method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the getTestClassesDirs() method instead.
The ConfigurableReport.setDestination(Object) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the method ConfigurableReport.setDestination(File) instead.
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to G:\android-sdks\ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to G:\android-sdks\ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to G:\android-sdks\ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

:preBuild UP-TO-DATE
:preReleaseBuild UP-TO-DATE
:checkReleaseManifest
:preDebugBuild UP-TO-DATE
:prepareAndroidArchLifecycleRuntime100Library
:prepareComAndroidSupportCustomtabs2610Library
:prepareComAndroidSupportSupportCompat2610Library
:prepareComAndroidSupportSupportCoreUi2610Library
:prepareComAndroidSupportSupportCoreUtils2610Library
:prepareComAndroidSupportSupportFragment2610Library
:prepareComAndroidSupportSupportMediaCompat2610Library
:prepareComAndroidSupportSupportV42610Library
:prepareComGoogleAndroidGmsPlayServicesAds1501Library
:prepareComGoogleAndroidGmsPlayServicesAdsBase1501Library
:prepareComGoogleAndroidGmsPlayServicesAdsIdentifier1501Library
:prepareComGoogleAndroidGmsPlayServicesAdsLite1501Library
:prepareComGoogleAndroidGmsPlayServicesBasement1501Library
:prepareComGoogleAndroidGmsPlayServicesGass1501Library
:prepareUnityAdsLibrary
:GoogleMobileAdsPlugin:preBuild UP-TO-DATE
:GoogleMobileAdsPlugin:preReleaseBuild UP-TO-DATE
:GoogleMobileAdsPlugin:checkReleaseManifest
:GoogleMobileAdsPlugin:prepareReleaseDependencies
:GoogleMobileAdsPlugin:compileReleaseAidl
:GoogleMobileAdsPlugin:compileReleaseNdk NO-SOURCE
:GoogleMobileAdsPlugin:compileLint
:GoogleMobileAdsPlugin:copyReleaseLint NO-SOURCE
:GoogleMobileAdsPlugin:mergeReleaseShaders
:GoogleMobileAdsPlugin:compileReleaseShaders
:GoogleMobileAdsPlugin:generateReleaseAssets
:GoogleMobileAdsPlugin:mergeReleaseAssets
:GoogleMobileAdsPlugin:mergeReleaseProguardFiles UP-TO-DATE
:GoogleMobileAdsPlugin:packageReleaseRenderscript NO-SOURCE
:GoogleMobileAdsPlugin:compileReleaseRenderscript
:GoogleMobileAdsPlugin:generateReleaseResValues
:GoogleMobileAdsPlugin:generateReleaseResources
:GoogleMobileAdsPlugin:packageReleaseResources
:GoogleMobileAdsPlugin:processReleaseManifest
:GoogleMobileAdsPlugin:generateReleaseBuildConfig
:GoogleMobileAdsPlugin:processReleaseResources
:GoogleMobileAdsPlugin:generateReleaseSources
:GoogleMobileAdsPlugin:incrementalReleaseJavaCompilationSafeguard
:GoogleMobileAdsPlugin:javaPreCompileRelease
:GoogleMobileAdsPlugin:compileReleaseJavaWithJavac
:GoogleMobileAdsPlugin:processReleaseJavaRes NO-SOURCE
:GoogleMobileAdsPlugin:transformResourcesWithMergeJavaResForRelease
:GoogleMobileAdsPlugin:transformClassesAndResourcesWithSyncLibJarsForRelease
:GoogleMobileAdsPlugin:mergeReleaseJniLibFolders
:GoogleMobileAdsPlugin:transformNativeLibsWithMergeJniLibsForRelease
:GoogleMobileAdsPlugin:transformNativeLibsWithSyncJniLibsForRelease
:GoogleMobileAdsPlugin:bundleRelease
:mopub:preBuild UP-TO-DATE
:mopub:preReleaseBuild UP-TO-DATE
:mopub:checkReleaseManifest
:mopub:prepareReleaseDependencies
:mopub:compileReleaseAidl
:mopub:compileReleaseNdk NO-SOURCE
:mopub:compileLint
:mopub:copyReleaseLint NO-SOURCE
:mopub:mergeReleaseShaders
:mopub:compileReleaseShaders
:mopub:generateReleaseAssets
:mopub:mergeReleaseAssets
:mopub:mergeReleaseProguardFiles UP-TO-DATE
:mopub:packageReleaseRenderscript NO-SOURCE
:mopub:compileReleaseRenderscript
:mopub:generateReleaseResValues
:mopub:generateReleaseResources
:mopub:packageReleaseResources
:mopub:processReleaseManifest
:mopub:generateReleaseBuildConfig
:mopub:processReleaseResources
:mopub:generateReleaseSources
:mopub:incrementalReleaseJavaCompilationSafeguard
:mopub:javaPreCompileRelease
:mopub:compileReleaseJavaWithJavac
:mopub:processReleaseJavaRes NO-SOURCE
:mopub:transformResourcesWithMergeJavaResForRelease
:mopub:transformClassesAndResourcesWithSyncLibJarsForRelease
:mopub:mergeReleaseJniLibFolders
:mopub:transformNativeLibsWithMergeJniLibsForRelease
:mopub:transformNativeLibsWithSyncJniLibsForRelease
:mopub:bundleRelease
:mopub-support:preBuild UP-TO-DATE
:mopub-support:preReleaseBuild UP-TO-DATE
:mopub-support:checkReleaseManifest
:mopub-support:prepareReleaseDependencies
:mopub-support:compileReleaseAidl
:mopub-support:compileReleaseNdk NO-SOURCE
:mopub-support:compileLint
:mopub-support:copyReleaseLint NO-SOURCE
:mopub-support:mergeReleaseShaders
:mopub-support:compileReleaseShaders
:mopub-support:generateReleaseAssets
:mopub-support:mergeReleaseAssets
:mopub-support:mergeReleaseProguardFiles UP-TO-DATE
:mopub-support:packageReleaseRenderscript NO-SOURCE
:mopub-support:compileReleaseRenderscript
:mopub-support:generateReleaseResValues
:mopub-support:generateReleaseResources
:mopub-support:packageReleaseResources
:mopub-support:processReleaseManifest
:mopub-support:generateReleaseBuildConfig
:mopub-support:processReleaseResources
:mopub-support:generateReleaseSources
:mopub-support:incrementalReleaseJavaCompilationSafeguard
:mopub-support:javaPreCompileRelease
:mopub-support:compileReleaseJavaWithJavac
:mopub-support:processReleaseJavaRes NO-SOURCE
:mopub-support:transformResourcesWithMergeJavaResForRelease
:mopub-support:transformClassesAndResourcesWithSyncLibJarsForRelease
:mopub-support:mergeReleaseJniLibFolders
:mopub-support:transformNativeLibsWithMergeJniLibsForRelease
:mopub-support:transformNativeLibsWithSyncJniLibsForRelease
:mopub-support:bundleRelease
:unity-android-resources:preBuild UP-TO-DATE
:unity-android-resources:preReleaseBuild UP-TO-DATE
:unity-android-resources:checkReleaseManifest
:unity-android-resources:prepareReleaseDependencies
:unity-android-resources:compileReleaseAidl
:unity-android-resources:compileReleaseNdk NO-SOURCE
:unity-android-resources:compileLint
:unity-android-resources:copyReleaseLint NO-SOURCE
:unity-android-resources:mergeReleaseShaders
:unity-android-resources:compileReleaseShaders
:unity-android-resources:generateReleaseAssets
:unity-android-resources:mergeReleaseAssets
:unity-android-resources:mergeReleaseProguardFiles UP-TO-DATE
:unity-android-resources:packageReleaseRenderscript NO-SOURCE
:unity-android-resources:compileReleaseRenderscript
:unity-android-resources:generateReleaseResValues
:unity-android-resources:generateReleaseResources
:unity-android-resources:packageReleaseResources
:unity-android-resources:processReleaseManifest
:unity-android-resources:generateReleaseBuildConfig
:unity-android-resources:processReleaseResources
:unity-android-resources:generateReleaseSources
:unity-android-resources:incrementalReleaseJavaCompilationSafeguard
:unity-android-resources:javaPreCompileRelease
:unity-android-resources:compileReleaseJavaWithJavac
:unity-android-resources:processReleaseJavaRes NO-SOURCE
:unity-android-resources:transformResourcesWithMergeJavaResForRelease
:unity-android-resources:transformClassesAndResourcesWithSyncLibJarsForRelease
:unity-android-resources:mergeReleaseJniLibFolders
:unity-android-resources:transformNativeLibsWithMergeJniLibsForRelease
:unity-android-resources:transformNativeLibsWithSyncJniLibsForRelease
:unity-android-resources:bundleRelease
:prepareReleaseDependencies
:compileReleaseAidl
:compileReleaseRenderscript UP-TO-DATE
:generateReleaseBuildConfig UP-TO-DATE
:generateReleaseResValues UP-TO-DATE
:generateReleaseResources UP-TO-DATE
:mergeReleaseResources
:processReleaseManifest
:processReleaseResources
:generateReleaseSources
:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:javaPreCompileRelease
:compileReleaseJavaWithJavac UP-TO-DATE
:compileReleaseNdk NO-SOURCE
:compileReleaseSources UP-TO-DATE
:lintVitalRelease
:mergeReleaseShaders UP-TO-DATE
:compileReleaseShaders UP-TO-DATE
:generateReleaseAssets UP-TO-DATE
:mergeReleaseAssets
:transformClassesWithDexForRelease FAILED
124 actionable tasks: 113 executed, 11 up-to-date
]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidJavaTools.RunJava (System.String args, System.String workingdir, System.Action`1 progress, System.String error)
UnityEditor.Android.GradleWrapper.Run (System.String workingdir, System.String task, System.Action`1 progress)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.Run (System.String workingdir, System.String task, System.Action`1 progress)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by aornelas** [comment]
same issue, different library; seems you have to remove more duplicate android jars...

**Comment by chauduyphanvu1** [comment]
@Kingkong302 - do a simple search for "v4" in your Unity project and make sure only 1 jar exists.

**Comment by Kingkong302** [comment]
hi @chauduyphanvu1 i integrated ads networks,unity and adcolony are working fine,but applovin and admob  ads are not working properly,i can see request for ads on dashboard when i send request for rewarded ad but ads is not displaying in device,can you please help me out.Thankyou

**Comment by Kingkong302** [comment]
@chauduyphanvu1  i have shared project through gmail.Please take a look.
Thankyou

**Comment by Kingkong302** [comment]
how to call multiple banners on screen,like one  bottom of screen and second at top?

**Comment by chauduyphanvu1** [comment]
@Kingkong302 - could you email support@mopub.com with any integration-related questions so we can further assist you? This is an adapter repo. Feel free to open a separate thread if you run into another issue.
