### ISSUE TITLE
OnRewardedVideoReceivedRewardEvent does not fire

### ISSUE THREAD

**Issue by chechulinYuri** [mopub/mopub-unity-mediation#29]
MoPubManager.OnRewardedVideoReceivedRewardEvent  does not fire for Unity Ads videos only. Facebook and Admob works good.

There is no errors in logs

Rewarded Video
Android
mopub 5.5.0
com.mopub.mediation.unityads-3.0.0.1
com.unity3d.ads.unity-ads-3.0.0
MoPub-UnityAds-Adapters-prod-1.0.1-Android.3.0.0.1-iOS.3.0.0.4

Also UnityAds works good, if we use only one rewarded ad unit for the game.
But we use multiple rewarded ad units (3) and one instertitial

**Comment by chauduyphanvu1** [comment]
@chechulinYuri - thanks for letting us know! First, could you fill out [this issue template](https://github.com/mopub/mopub-unity-mediation/blob/master/ISSUE_TEMPLATE.md) to make sure you have tried everything and gathered sufficient information for us to debug the issue? Second, could you describe your use case a bit more (how are you requesting ads, do you have code snippets, etc.)?

Vu Chau
MoPub SDK Team

**Comment by praleks** [comment]
Same here, no callback for unity ads

**Comment by newstrong** [comment]
Same here, no callback for unity ads

**Comment by chauduyphanvu1** [comment]
@praleks @newstrong - are you able to provide a sample Unity project where you saw that callback issue? Ensure you're using the latest Unity Ads adapters too. Thanks!

**Comment by praleks** [comment]
I solved it by removing built-in unity ads package

**Comment by chauduyphanvu1** [comment]
Closing due to not having repro data.
