### ISSUE TITLE
Error on Interstitial and rewarded video

### ISSUE THREAD

**Issue by mubshar1** [mopub/mopub-unity-mediation#34]
1. **What is the issue?**
    see Screenshots 

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (Interstitial, Rewarded Video)
        > Interstitial, Rewarded Video
    * **Platform** (*Android, iOS, Unity*)
        > Unity
    * **MoPub SDK Version**
        > 5.6
   * **Adapter
        > admob-17.1.2.4
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > 43e15d28dc934bf6ab3006b930e7f2fe  
        > 31af98db968f47d6bfdbfef316b70d03
    * **Device model and OS Version**
        > Android 8.0
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. show ads
        
   
![err1](https://user-images.githubusercontent.com/45542019/55055741-ceafa200-5085-11e9-9537-d4f6c433e774.PNG)
![err2](https://user-images.githubusercontent.com/45542019/55055750-d3745600-5085-11e9-9b76-cda3f770105f.PNG)

    * **Evidence** (if available)
        > Attach logs (device/network), mini debug builds (source code preferably), stack traces, screenshots / screen recordings, etc.

**Comment by chauduyphanvu1** [comment]
@mubshar1 - thanks for letting us know! We'll take a look and deploy a fix for this issue.

Vu Chau
MoPub SDK Team

**Comment by mubshar1** [comment]
@chauduyphanvu1  Any Update?

**Comment by chauduyphanvu1** [comment]
@mubshar1 - the work is in progress. We expect the upcoming Unity package for AdMob to have the fix.

**Comment by chauduyphanvu1** [comment]
This issue will be gone in the next AdMob adapter release due to the removal of `onPause()` and `onResume()` in https://github.com/mopub/mopub-android-mediation/pull/155/files#diff-afe59c7d6dc997d5918029cc2365d3c8L90.

**Comment by chauduyphanvu1** [comment]
This issue has been addressed in [v17.2.0.0](https://github.com/mopub/mopub-android-mediation/commit/7c8a7924889c06612bffca2480f8754f27fc0f45) of the Android AdMob adapters. Let us know if you continue to see the issue!
