### ISSUE TITLE
Pod install failure while using AdMob and Firebase

### ISSUE THREAD

**Issue by OsmanSenol** [mopub/mopub-unity-mediation#39]
1. **What is the issue?**
    > Error while installing cocoapods. Firebase v6.0.0 and AdMob v7.43.0 support different versions of GoogleAppMeasurement library. AdMob has released a new version(v7.44.0). Now, it supports GoogleAppMeasurement v6.0.0. Updating the adapter with AdMob v7.44.0 support can solve the problem.

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > -
    * **Platform** (*Android, iOS, Unity*)
        > Unity,iOS
    * **MoPub SDK Version**
        > 5.7.0
    * **Mediation SDK Name & Version**
        > AdMob v7.43.0
    * **Mediation Adapter Version**
        > 7.43.0.0
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > -
    * **Device model and OS Version**
        > -
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. Create an empty unity project
        > 2. Import Firebase v6.0.0
        > 3. Import MoPub SDK v5.7.0
        > 4. Import AdMob Adapter v7.43.0.0
        > 5. Build project
        > 6. Run `pod install` in exported xcode project
    * **Observed behavior**
        > Error while installing pods
    * **Expected behavior** (if known)
        > Successful pod installation
    * **Evidence** (if available)
        > Log : 
[!] CocoaPods could not find compatible versions for pod "GoogleAppMeasurement":
  In Podfile:
    Firebase/Analytics (= 6.0.0) was resolved to 6.0.0, which depends on
      Firebase/Core (= 6.0.0) was resolved to 6.0.0, which depends on
        FirebaseAnalytics (= 6.0.0) was resolved to 6.0.0, which depends on
          GoogleAppMeasurement (= 6.0.0)
    MoPub-AdMob-Adapters/Network (= 7.43.0.0) was resolved to 7.43.0.0, which depends on
      Google-Mobile-Ads-SDK (= 7.43.0) was resolved to 7.43.0, which depends on
        GoogleAppMeasurement (~> 5.7)

**Comment by chauduyphanvu1** [comment]
@OsmanSenol, thanks for letting us know! v7.44.0.0 is under internal testing, and once released, it'll fix this issue you are seeing with CocoaPods unable to resolve the different versions of GoogleAppMeasurement. Feel free to watch the https://github.com/mopub/mopub-ios-mediation repository for updates on that.

Vu Chau
MoPub SDK Team

**Comment by chauduyphanvu1** [comment]
This issue should have been resolved via https://github.com/mopub/mopub-unity-mediation/commit/313592d4d34c5de7cec9da48a55efc05f612f737 just now. Please try again by either downloading this new .unitypackage binary or integrating it via the [SDK Manager](https://developers.mopub.com/publishers/unity/get-started/#step-1-integrate-the-plugin-and-mediation-adapters), and let us know if you still face the issue!
