### ISSUE TITLE
Admob ads not showing after, app is closed or force closed.

### ISSUE THREAD

**Issue by BinuVargheseC** [mopub/mopub-unity-mediation#41]
1. **What is the issue?**
    >
Mopub SDK  5.9.0

Unity 2019.1.13f1

Admob Adapter 1.3.0

Admob ads loading first time.

After app is closed or force closed.Admob stop showing ads.

But all other Mediation network works fine.

Admob will start showing ads if we clear the app data.

I dont not this is a issue from your side please check this.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > Interstitial, Rewarded Video
    * **Platform** (*Android, iOS, Unity*)
        > Unity*
    * **MoPub SDK Version**
        > 5.9.0
    * **Mediation SDK Name & Version**
        > Admob Adapter 1.3.0
    * **Mediation Adapter Version**
        >Admob Adapter 1.3.0
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > 3d40d4134cf7447781dd35df58d8d12e,d2666bd0e5bf4900abeb3dfc8fe52881

**Comment by chauduyphanvu** [comment]
@BinuVargheseC, how consistently are you seeing the issue with AdMob ads failing to play on app closes? I tested your ad unit IDs with our Unity sample project ([available here](https://github.com/mopub/mopub-unity-sdk/tree/master/unity-sample-app)) but did not reproduce the issue when I closed and reopened the app (I did not have to clear the app's storage and cache). 

If you haven't, try reproducing the issue in our Unity sample project. If the issue occurs, send us the project. If the issue doesn't occur, feel free to share with us your ow Unity project as this could be an implementation-related issue. One more thing to check is any frequency capping configuration you might have set on your AdMob ad units. Make sure they are not capped (you can also use [AdMob test ads](https://developers.google.com/admob/android/test-ads) to validate your implementation so you can rule out any serving issues).

Vu Chau
MoPub Support Team

**Comment by BinuVargheseC** [comment]
The issue does not appear while using the Admob Test Ads only for real ads.

**Comment by BinuVargheseC** [comment]
I think i don't have any issue in loading ads because when I clear the app cache ads loading without any delay.

**Comment by chauduyphanvu** [comment]
Thank you for the confirmation. In that case, since the issue does not manifest with test ads, your SDKs implementation seems valid. As a next step, I recommend getting in touch with Google so they can look into your ad unit ID configuration on the dashboard. If you have any console logs when the AdMob ad requests fail, feel free to share them with Google as well.

Let us know if you have any other questions!

**Comment by BinuVargheseC** [comment]
when I uploaded the app to google play then installed from google play it worked fine. I am not quite sure that was the reason for this issue. But it solved my issue.

**Comment by BledyEdge** [comment]
Hi i have imported mopub sdk in unity, and did not added any other netwrk sdks, test ads of mopub are not showing even of demo scene,Can one can help please?

**Comment by chauduyphanvu** [comment]
@BledyEdge, please open a separate issue so we can thoroughly assist you. Thank you!

**Comment by BledyEdge** [comment]
> @BledyEdge, please open a separate issue so we can thoroughly assist you. Thank you!

Aright Thank you

**Comment by chauduyphanvu** [comment]
@Stole1703, could you open a separate issue so we can track and investigate it properly? Please include relevant details, including your ad unit ID, device/console logs, adapter/SDK versions, and a mini sample project where we can reproduce the issue. 

Thank you!
