### ISSUE TITLE
MoPub 5.11.0 with Admob and Facebook adapters not building in Unity for iOS

### ISSUE THREAD

**Issue by JabluszkoPL** [mopub/mopub-unity-mediation#43]
1. **What is the issue?**
    MoPub 5.11.0 with Admob and Facebook not building in Unity for iOS 

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Platform** (*Android, iOS, Unity*)
        > Unity - iOS
   * **Environment**
        > Unity 2019.1
        > Xcode 11.3.1
    * **MoPub SDK Version**
        > 5.11.0
    * **Mediation SDK Name & Version**
        > Facebook - 1.4.4, AdMob - 1.3.9
    * **Mediation Adapter Version**
        > Provide the data here
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > FacebookAudienceNetwork-Adapters', '5.6.0.0', 'MoPub-AdMob-Adapters', '7.53.1.0'
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. Install MoPub SDK 5.11.0
        > 2. Install Facebook adapter 1.4.4, AdMob adapter 1.3.9
        > 3. Build Unity Project on iOS
    * **Observed behavior**
        > Error during build process: MPNativeAdRenderer.h -  not found
    * **Expected behavior** (if known)
        > Adapters build without fail

**Comment by chauduyphanvu** [comment]
@JabluszkoPL, thanks for letting us know! We've updated the Facebook Unity package at  https://github.com/mopub/mopub-unity-mediation/commit/48af1ad2dc1b2e0874eebd1357a87e37eee90bd4. Please download that version of the Facebook adapters.

A fix for the AdMob adapters is under way.

**Comment by chauduyphanvu** [comment]
The AdMob adapters have been fixed in https://github.com/mopub/mopub-unity-mediation/commit/cfccbc9d6306c69f9c2f12235914e694b9711c39. Let us know if you continue seeing the issue!
