### ISSUE TITLE
Mopub Unity mediation FacebookAudienceNetwork supports DataProcessingOptions ?

### ISSUE THREAD

**Issue by psstevenchan** [mopub/mopub-unity-mediation#44]
How to set FacebookAudienceNetwork DataProcessingOptions from Mopub Unity SDK?
https://developers.facebook.com/docs/audience-network/support/faq/ccpa

**Comment by chauduyphanvu** [comment]
@psstevenchan, we aren't able to comment on how publishers should handle CCPA in mediation. Please reach out to Facebook Audience Network to understand if there are any required actions on publishers. Thank you!

Vu Chau
MoPub Team

**Comment by psstevenchan** [comment]
Facebook Audience Network SDK provided API on both iOS SDK, v5.10+ and Android SDK, v5.10+, But the Mopub mediation FacebookAudienceNetwork didn't allow to call those api.

iOS:
FBAdSettings setDataProcessingOptions.
To explicitly not enable Limited Data Use (LDU) mode, use:
[FBAdSettings setDataProcessingOptions:@[]];
To enable LDU for users and specify user geography, use:
[FBAdSettings setDataProcessingOptions:@[@"LDU"] country:1 state:1000];
To enable LDU for users with geolocation, use:
[FBAdSettings setDataProcessingOptions:@[@"LDU"] country:0 state:0];

Android:
To explicitly not enable LDU mode, use:
AdSettings.setDataProcessingOptions(new String[] {}) 
To enable LDU for users and specify user geography, use:
AdSettings.setDataProcessingOptions(new String[] {"LDU"}, 1, 1000);
To enable LDU for users with geolocation, use:
AdSettings.setDataProcessingOptions(new String[] {"LDU"}, 0, 0);

**Comment by chauduyphanvu** [comment]
@psstevenchan, please notify Facebook directly from your app by calling the respective API for your platform. MoPub does not handle CCPA on behalf of mediation partners.

**Comment by psstevenchan** [comment]
In MoPub Unity SDK, I can't call FacebookAudienceNetwork's respective API through c#

**Comment by chauduyphanvu** [comment]
I see what you are referring to. Please communicate your use case to Facebook so they can expose a C# API or provide further guidance on this. 

Thanks!

**Comment by Arrnav** [comment]
Hi, I have solved this problem in Unity by using the first approach outlined [https://stackoverflow.com/questions/66050765/how-to-set-setadvertisertrackingenabled-with-ironsource-unity](url)

For MoPub or any other plugin for ads, it's just a matter of finding the right .m file for iOS (Not sure about Android) and editing it by adding the native FB line from the docs `[FBAdSettings setDataProcessingOptions:@[]];`
