### ISSUE TITLE
Chartboost 8.2.0.1 Initialization/Consent Crash

### ISSUE THREAD

**Issue by hmertkahraman** [mopub/mopub-unity-mediation#45]
This issue is to carry the original issue created by @simon002 on Unity SDK repostirory: [mopub-unity-sdk/issues/135 ](https://github.com/mopub/mopub-unity-sdk/issues/135) to this Unity mediation repository, as the issue is mediation related.
Full summary of the issue is present [here](https://github.com/mopub/mopub-unity-sdk/issues/135).

**Summary**
Chartboost SDK crashes upon upgrading to 8.2.0.1.

**Comment by hmertkahraman** [comment]
Hi @simon002,

We're investigating the issue with Chartboost directly as well, however the information on the logs are not comprehensive. 

- May we ask if you have the **exact/full** crash stack trace, which XCode prints out, mentioning the exception type
![image](https://user-images.githubusercontent.com/47573140/89660842-94415080-d8da-11ea-9c74-cc7aabbf4ca8.png)

- Also, when does this crash exactly happen, upon startup of the app, or during MoPub initialization, or during an ad request?

- How do you handle your GDPR Consent, do you use MoPub owned Consent dialog, or your own?

Please let us know.

Thanks,
Mert

**Comment by simon002** [comment]
> Hi @simon002,
> 
> We're investigating the issue with Chartboost directly as well, however the information on the logs are not comprehensive.
> 
> * May we ask if you have the **exact/full** crash stack trace, which XCode prints out, mentioning the exception type
>   ![image](https://user-images.githubusercontent.com/47573140/89660842-94415080-d8da-11ea-9c74-cc7aabbf4ca8.png)
> * Also, when does this crash exactly happen, upon startup of the app, or during MoPub initialization, or during an ad request?
> * How do you handle your GDPR Consent, do you use MoPub owned Consent dialog, or your own?
> 
> Please let us know.
> 
> Thanks,
> Mert

The crash log:
<img width="1272" alt="fff" src="https://user-images.githubusercontent.com/10241848/89749699-67b84f00-dafb-11ea-86c8-1904ad2e40ba.png">

The crash happen when during MoPub initialization.

I use MoPub owned Consent dialog.
<img width="1396" alt="mm" src="https://user-images.githubusercontent.com/10241848/89749799-d9909880-dafb-11ea-814d-db4ee227431d.png">

**Comment by hmertkahraman** [comment]
Hi @simon002 ,

Thanks for the information, we will get back to you on this after further troubleshooting with Chartboost.

Thanks,
Mert

**Comment by hmertkahraman** [comment]
Hi @simon002,

We reached out to Chartboost to learn what does Chartboost.m 62:12 specifically do (which is the crash on your setup). Will update here once we learn more.

Thanks,
Mert

**Comment by hmertkahraman** [comment]
Hi @simon002 ,

Chartboost team advised us that they identified the issue, and they are working on it. They will release a fix for this issue on their next SDK release (timeline is unknown at this time).

Until then, they filed a PR that bypasses this issue from happening. Please find the PR [here](https://github.com/mopub/mopub-ios-mediation/pull/321/files). 

CB team informed us that, crash only happens when the first Chartboost method called is the setLoggingLevel method with CBLoggingLevelVerbose. If you change the logging level or use a different method as your first Chartboost call, then that avoids the issue.

You can apply this PR on your end to Chartboost adapters you use to overcome the fix. Once the new version with fix is out, you can upgrade and resolve it. Please follow our Mediation Integration Tool for updates on Chartboost. 

To alter your adapter code for the PR, you will need a manual installation for Chartboost, you can refer to [here](https://developers.mopub.com/publishers/unity/integrate/#option-2-integrate-manually) (specifically Step 3) on our docs for Unity.

Please let us know if you have any further questions.

Thanks,
Mert

**Comment by hmertkahraman** [comment]
Hi @simon002 ,

New Chartboost adapters are released with the fix mentioned above. You can simply upgrade to those from MoPub Manager Plugin on Unity.

Thanks,
Mert

**Comment by simon002** [comment]
> Hi @simon002 ,
> 
> New Chartboost adapters are released with the fix mentioned above. You can simply upgrade to those from MoPub Manager Plugin on Unity.
> 
> Thanks,
> Mert
I Get it. Thanks very much.
